[package]
authors = ["sope <shenshouer51@gmail.com>"]
edition = "2018"
name = "eldiro"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12"
